# Generated by Django 3.1.4 on 2021-01-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_product_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
