# Generated by Django 3.1.4 on 2021-01-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fields',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
