# Generated by Django 3.1.4 on 2021-01-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20210111_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='types',
            new_name='name',
        ),
    ]
