# Generated by Django 3.1.4 on 2021-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20210111_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Neapolitan Pizza', 'Neapolitan Pizza'), ('Chicago Pizza', 'Chicago Pizza'), ('New York-Style Pizza', 'New York-Style Pizza'), ('Greek Pizza', 'Greek Pizza'), ('California Pizza', 'California Pizza'), ('Capricciosa Pizza', 'Capricciosa Pizza'), ('Mexicana Pizza', 'Mexicana Pizza'), ('Quattro Stagioni Pizza', 'Quattro Stagioni Pizza'), ('Quattro Formagi Pizza', 'Quattro Formagi Pizza')], max_length=255, null=True),
        ),
    ]
