# Generated by Django 3.1.4 on 2021-01-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20210111_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Neapolitan Pizza', 'Neapolitan Pizza'), ('Chicago Pizza', 'Chicago Pizza'), ('New York-Style Pizza', 'New York-Style Pizza'), ('Greek Pizza', 'Greek Pizza'), ('California Pizza', 'California Pizza'), ('Capricciosa Pizza', 'Capricciosa Pizza'), ('Mexicana Pizza', 'Mexicana Pizza'), ('Quattro Stagioni Pizza', 'Quattro Stagioni Pizza'), ('Quattro Formaggi Pizza', 'Quattro Formaggi Pizza')], max_length=255, null=True),
        ),
    ]
