# Generated by Django 3.1.4 on 2021-01-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0014_auto_20210113_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzas.order'),
        ),
    ]
