# Generated by Django 3.1.4 on 2021-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0015_order_product_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA')], max_length=250, null=True),
        ),
    ]
