# Generated by Django 3.1.4 on 2021-01-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0016_auto_20210113_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzas.product'),
        ),
    ]
