# Generated by Django 3.1.4 on 2021-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0018_auto_20210113_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=255, null=True),
        ),
    ]
