# Generated by Django 3.1.4 on 2021-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0019_auto_20210114_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Neapolitan Pizza', 'Neapolitan Pizza'), ('Chicago Pizza', 'Chicago Pizza'), ('New York-Style Pizza', 'New York-Style Pizza'), ('Greek Pizza', 'Greek Pizza'), ('California Pizza', 'California Pizza'), ('Capricciosa Pizza', 'Capricciosa Pizza'), ('Mexican Pizza', 'Mexican Pizza'), ('Quattro Stagioni Pizza', 'Quattro Stagioni Pizza'), ('Quattro Formaggi Pizza', 'Quattro Formaggi Pizza')], max_length=255, null=True),
        ),
    ]
