# Generated by Django 3.1.4 on 2021-01-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0021_product_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
