# Generated by Django 3.1.4 on 2021-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0026_auto_20210119_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('FINALIZATA', 'FINALIZATA')], default='ACTIVA', max_length=250, null=True),
        ),
    ]
