# Generated by Django 3.1.4 on 2021-01-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0027_auto_20210119_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
