# Generated by Django 3.1.4 on 2021-01-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0031_auto_20210126_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='price',
        ),
    ]
