# Generated by Django 3.1.4 on 2021-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0033_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
